USE [master]
GO
/****** Object:  Database [QuanLyPhongTro]    Script Date: 10/10/2017 3:10:55 PM ******/
CREATE DATABASE [QuanLyPhongTro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyPhongTro', FILENAME = N'D:\Visual_data\Bin_demo\QuanLyPhongTro.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QuanLyPhongTro_log', FILENAME = N'D:\Visual_data\Bin_demo\PQuanLyPhongTro_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [QuanLyPhongTro] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyPhongTro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanLyPhongTro] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QuanLyPhongTro] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyPhongTro] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyPhongTro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanLyPhongTro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QuanLyPhongTro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLyPhongTro] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanLyPhongTro] SET  MULTI_USER 
GO
ALTER DATABASE [QuanLyPhongTro] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLyPhongTro] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLyPhongTro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanLyPhongTro] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [QuanLyPhongTro]
GO
/****** Object:  Table [dbo].[ChitietPhong]    Script Date: 10/10/2017 3:10:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChitietPhong](
	[MaPhong] [varchar](5) NOT NULL,
	[IdNguoi] [int] identity(1,1) NOT NULL,
	[TienCoc] [money] NULL,
	[SoNguoi] [int] NULL,
	[TinhTrang] [bit] NULL,
	[ChuPhong] [bit] NULL,
PRIMARY KEY CLUSTERED
(
	[IdNguoi] ASC,
	[MaPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LoaiPhong]    Script Date: 10/10/2017 3:10:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LoaiPhong](
	[MaLoai] [int] IDENTITY(1,1) NOT NULL,
	[TenLoai] [varchar](20) NULL,
	[GiaPhong] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NguoiTro]    Script Date: 10/10/2017 3:10:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NguoiTro](
	[IdNguoi] [int] IDENTITY(1,1) NOT NULL,
	[HoTen] [varchar](50) NULL,
	[NamSinh] [date] NULL,
	[Cmnd] [int] NULL,
	[SoDT] [int] NULL,
	[NgayVao] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdNguoi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Phong]    Script Date: 10/10/2017 3:10:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Phong](
	[Maloai] [int] NULL,
	[MaPhong] [varchar](5) NOT NULL,
	[TenPhong] [varchar](20) NULL,
	[Internet] [money] NULL,
	[Rac] [money] NULL,
	[Nuoc] [money] NULL,
	[Dien] [money] NULL,
	[ChiPhiKhac] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TienPhongThang]    Script Date: 10/10/2017 3:10:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TienPhongThang](
	[MaPhong] [varchar](5) NOT NULL,
	[SoDienCu] [int] NULL,
	[SoDienMoi] [int] NULL,
	[SoNuocCu] [int] NULL,
	[SoNuocMoi] [int] NULL,
	[TienPhong] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaPhong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ChitietPhong]  WITH CHECK ADD FOREIGN KEY([IdNguoi])
REFERENCES [dbo].[NguoiTro] ([IdNguoi])
GO
ALTER TABLE [dbo].[ChitietPhong]  WITH CHECK ADD FOREIGN KEY([MaPhong])
REFERENCES [dbo].[Phong] ([MaPhong])
GO
ALTER TABLE [dbo].[Phong]  WITH CHECK ADD FOREIGN KEY([Maloai])
REFERENCES [dbo].[LoaiPhong] ([MaLoai])
GO
ALTER TABLE [dbo].[TienPhongThang]  WITH CHECK ADD FOREIGN KEY([MaPhong])
REFERENCES [dbo].[Phong] ([MaPhong])
GO
USE [master]
GO
ALTER DATABASE [QuanLyPhongTro] SET  READ_WRITE 
GO
