//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bin_BB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietPhong
    {
        public string MaPhong { get; set; }
        public int IdNguoi { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<bool> ChuPhong { get; set; }
    
        public virtual NguoiTro NguoiTro { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
