//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bin_BB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChitietPhongs = new HashSet<ChitietPhong>();
        }
    
        public Nullable<int> Maloai { get; set; }
        public string MaPhong { get; set; }
        public Nullable<decimal> Internet { get; set; }
        public Nullable<decimal> Rac { get; set; }
        public Nullable<decimal> Nuoc { get; set; }
        public Nullable<decimal> Dien { get; set; }
        public Nullable<decimal> ChiPhiKhac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietPhong> ChitietPhongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual TienPhongThang TienPhongThang { get; set; }
    }
}
