//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bin_BB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienPhongThang
    {
        public string MaPhong { get; set; }
        public Nullable<int> SoDienCu { get; set; }
        public Nullable<int> SoDienMoi { get; set; }
        public Nullable<int> SoNuocCu { get; set; }
        public Nullable<int> SoNuocMoi { get; set; }
        public Nullable<decimal> TienPhong { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
